### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shanow7** [dalunacrobate/DaProfiler#5]
[~/DaProfiler]
└─$ python3 profiler.py -n jean -ln reno -l True       
Author : Dalunacrobate | Mail : daluna_pro@protonmail.ch
21:04:58 - Searching for Facebook accounts ...
21:04:59 - Searching for Twitter accounts ...
21:05:00 - Searching for Death records ...
21:05:01 - Searching for Company ...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "profiler.py", line 51, in <module>
    bfmtv_results = dirigeants_bfmtv.bfmtv_search(name=name,pren=pren)
  File "/home/shanow/DaProfiler/modules/dirigeants_bfmtv.py", line 5, in bfmtv_search
    r = requests.get("https://dirigeants.bfmtv.com/recherche/q/{}5+{}6".format(name,pren))
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/shanow/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))

can you help?

**Comment by dalunacrobate** [comment]
> tries exceeded with url: /recherche/q/reno5+jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsup

Try with that new update

**Comment by shanow7** [comment]
python3 profiler.py -n jean -ln reno -l True
Traceback (most recent call last):
  File "/home/shanow/OSINT/DaProfiler/profiler.py", line 18, in <module>
    from modules  import holehe_module
  File "/home/shanow/OSINT/DaProfiler/modules/holehe_module.py", line 14, in <module>
    from holehe.modules.social_media.protonmail import *
ModuleNotFoundError: No module named 'holehe.modules.social_media.protonmail'

**Comment by Raykhou** [comment]
Traceback (most recent call last):
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\gael machuron\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='scylla.so', port=443): Max retries exceeded with url: /search?q=email:lulugamer41@gmail.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DaProfiler\profiler.py", line 207, in <module>
    scylla_results = scylla_sh.scylla_search(email=i)
  File "C:\DaProfiler\modules\scylla_sh.py", line 4, in scylla_search
    r = requests.get('https://scylla.so/search?q=email:{}'.format(email))
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scylla.so', port=443): Max retries exceeded with url: /search?q=email:lulugamer41@gmail.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

**Comment by dalunacrobate** [comment]
> Traceback (most recent call last):
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
> conn = connection.create_connection(
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
> raise err
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
> sock.connect(sa)
> TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
> httplib_response = self._make_request(
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
> self._validate_conn(conn)
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
> conn.connect()
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
> conn = self._new_conn()
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
> raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
> resp = conn.urlopen(
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
> retries = retries.increment(
> File "C:\Users\gael machuron\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 573, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='scylla.so', port=443): Max retries exceeded with url: /search?q=email:[lulugamer41@gmail.com](mailto:lulugamer41@gmail.com) (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\DaProfiler\profiler.py", line 207, in
> scylla_results = scylla_sh.scylla_search(email=i)
> File "C:\DaProfiler\modules\scylla_sh.py", line 4, in scylla_search
> r = requests.get('[https://scylla.so/search?q=email:{}'.format(email)](https://scylla.so/search?q=email:%7B%7D'.format(email)))
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
> return request('get', url, params=params, **kwargs)
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "C:\Users(mon nom)\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scylla.so', port=443): Max retries exceeded with url: /search?q=email:[lulugamer41@gmail.com](mailto:lulugamer41@gmail.com) (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D8E69CB370>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

Fixed

**Comment by dalunacrobate** [comment]
> [~/DaProfiler]
> └─$ python3 profiler.py -n jean -ln reno -l True
> Author : Dalunacrobate | Mail : [daluna_pro@protonmail.ch](mailto:daluna_pro@protonmail.ch)
> 21:04:58 - Searching for Facebook accounts ...
> 21:04:59 - Searching for Twitter accounts ...
> 21:05:00 - Searching for Death records ...
> 21:05:01 - Searching for Company ...
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
> httplib_response = self._make_request(
> File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
> self._validate_conn(conn)
> File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn conn.connect() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 361, in connect self.sock = ssl_wrap_socket( File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
> return self.sslsocket_class._create(
> File "/usr/lib/python3.8/ssl.py", line 1040, in _create
> self.do_handshake()
> File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
> self._sslobj.do_handshake()
> ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
> resp = conn.urlopen(
> File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
> retries = retries.increment(
> File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 439, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "profiler.py", line 51, in
> bfmtv_results = dirigeants_bfmtv.bfmtv_search(name=name,pren=pren)
> File "/home/shanow/DaProfiler/modules/dirigeants_bfmtv.py", line 5, in bfmtv_search
> r = requests.get("[https://dirigeants.bfmtv.com/recherche/q/{}5+{}6".format(name,pren)](https://dirigeants.bfmtv.com/recherche/q/%7B%7D5+%7B%7D6%22.format(name,pren)))
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
> return request('get', url, params=params, **kwargs)
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "/home/shanow/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))
> 
> can you help?

Fixed
